package com.quizkar.dao.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import com.quizkar.dao.UsersDAO;
import com.quizkar.entities.Users;
import com.quizkar.util.DBUtil;
import com.quizkar.util.PasswordUtils;

public class UsersDAOImpl implements UsersDAO{

	//Returns UserId of added users
	@Override
	public Integer addUser(Users user) throws SQLException
	{
																		// (RETURNING user_id) This part is used here because we want an user_id generated by postgresql
		String query = "INSERT INTO users (username, email, password, role) VALUES (?, ?, ?, ?) RETURNING user_id";
		Integer generatedId = null;
		
		//Hash the password before inserting
		String securedPassword = PasswordUtils.generateSecurePassword( user.getPassword() );
		
		try (Connection connection = DBUtil.getConnection();
		     PreparedStatement preparedStatement = connection.prepareStatement(query)) {
			
//			connection.setAutoCommit(false);
			
		    preparedStatement.setString(1, user.getUserName());
		    preparedStatement.setString(2, user.getEmail());
		    preparedStatement.setString(3, securedPassword);
		    preparedStatement.setString(4, user.getRole());

		    ResultSet resultSet = preparedStatement.executeQuery();

		    
		    if (resultSet.next()) {
		        generatedId = resultSet.getInt("user_id");
//		        System.out.println("Inserted User ID: " + generatedId);
		    }
		}
		catch (SQLException e) {
		    e.printStackTrace();
		    throw e; 
		}
		return generatedId;
		
	}

	
	//
	@Override
	public Integer updateUser(Users user) throws SQLException
	{
		
//		Connection connection = null;
		String query = "UPDATE users SET username = ?, email = ?, password = ? WHERE user_id = ?";
		Integer affectedRows = 0;
		
		try(Connection connection  = DBUtil.getConnection()) {
			
			connection.setAutoCommit(false);
			
			try( PreparedStatement preparedStatement = connection.prepareStatement(query)){
				
				preparedStatement.setString(1, user.getUserName());
				preparedStatement.setString(2, user.getEmail());
				preparedStatement.setString(3, user.getPassword());
				preparedStatement.setInt(4, user.getUserId());
				
				affectedRows = preparedStatement.executeUpdate();
				connection.commit();
			}
			catch(SQLException e) {
				e.printStackTrace();
				if(connection != null) {
					try {
						connection.rollback();
					}
					catch(SQLException rollBackEX) {
						rollBackEX.printStackTrace();
					}
				}
				throw e;
			}
		}
		return affectedRows;
	}
	
	
	@Override
	public Users validateUser(Users user) throws SQLException
	{
		
		//email and username are unique, so we will get all records with matching username or email
		//And then, we will get all his info, with the hashed password, 
		//Then we will check the hashed password, if it matches, then we will return user object else, null
		
		Users retUser = null;
		String query = "SELECT * FROM users WHERE username = ? OR email = ? ";
		
		try(Connection connection = DBUtil.getConnection();
			PreparedStatement preparedStatement = connection.prepareStatement(query))
		{
			preparedStatement.setString(1, user.getUserName());
			preparedStatement.setString(2, user.getEmail());

			try(ResultSet resultSet = preparedStatement.executeQuery()){
				if(resultSet.next()) {
					retUser = mapResultSetToUsers(resultSet);
					
					//This is hashed password
					String securedPassword = resultSet.getString("password");
					
					//If password is valid return user, else null
					if( PasswordUtils.checkPassword(user.getPassword(), securedPassword) ) {
						return retUser;
					}
					else {
						return null;
					}
				}
			}
		}
		
		return retUser;
	}
	
	
	@Override
	public Users getUserById(int userId) throws SQLException {
		String query = "SELECT * FROM users WHERE user_id = ? ";
		
		try (Connection connection = DBUtil.getConnection();
			PreparedStatement preparedStatement = connection.prepareStatement(query)){
			
			preparedStatement.setInt(1, userId);
			
			try(ResultSet resultSet = preparedStatement.executeQuery()){
				if(resultSet.next()) {
					return  mapResultSetToUsers(resultSet);
				}
			}
		}
		return null;
	}
	
	
	@Override
	public Users getUser(Users user) throws SQLException
	{
		
		String query = "SELECT * FROM users WHERE username = ? OR email = ?";
		
		try(Connection connection = DBUtil.getConnection();
			PreparedStatement preparedStatement = connection.prepareStatement(query))
		{
			preparedStatement.setString(1, user.getUserName());
			preparedStatement.setString(2, user.getEmail());
			
			try(ResultSet resultSet = preparedStatement.executeQuery()){
				if(resultSet.next()) {
					return  mapResultSetToUsers(resultSet);
				}
			}
		}		
		return null;
	}
	
	
	@Override
	public Integer deleteUser(Integer userId) throws SQLException
	{
		Integer affectedRow = 0;
		final String query = "DELETE FROM users WHERE user_id = ?";
		
		try (Connection connection = DBUtil.getConnection()){
			
			connection.setAutoCommit(false);
			
			try( PreparedStatement preparedStatement  = connection.prepareStatement(query)) {
					
				preparedStatement.setInt(1, userId);
				
				affectedRow = preparedStatement.executeUpdate();
				
				connection.commit();
			}
			catch(SQLException e) {
				if(connection != null) {
					connection.rollback();
				}
				throw e;
			}
			
		}
		return affectedRow;
	}
	
	

	
	//Return the total number of users registred in application
	@Override
	public Integer getTotalUsers() throws SQLException{
		
		String query = "SELECT user_count FROM registration_count";
		
		try(Connection connection = DBUtil.getConnection();
			PreparedStatement preparedStatement = connection.prepareStatement(query))
		{
			
			try(ResultSet resultSet = preparedStatement.executeQuery()){
				if(resultSet.next()) {
					return resultSet.getInt("user_count");
				}
			}
		}		
		return 0;
	}
	
	@Override
	public List<Users> getAllUsers() throws SQLException{ 
		
		List<Users> users = new ArrayList<Users>();
		String query = "SELECT * FROM users";
		int i = 0;
		
		try(Connection connection = DBUtil.getConnection();
				PreparedStatement preparedStatement = connection.prepareStatement(query))
			{
				try(ResultSet resultSet = preparedStatement.executeQuery()){
					while(resultSet.next()) {
						 users.add( mapResultSetToUsers(resultSet) );
						 //users.get(i++).setPassword(  resultSet.getString("password")  );
					}
				}
			}
		
		return  users;
		
	}
	
	
	//Update userRegistration count for every registration returns row affected
	@Override
	public Integer updateTotalUser() throws SQLException{
		
		String query = "UPDATE registration_count SET user_count = (SELECT user_count FROM registration_count) + 1";
		Integer affectedRows = 0;
		
		try(Connection connection  = DBUtil.getConnection()) {
			
			connection.setAutoCommit(false);
			
			try( PreparedStatement preparedStatement = connection.prepareStatement(query)){
				
				affectedRows = preparedStatement.executeUpdate();
				connection.commit();
			}
			catch(SQLException e) {
				e.printStackTrace();
				if(connection != null) {
					try {
						connection.rollback();
					}
					catch(SQLException rollBackEX) {
						rollBackEX.printStackTrace();
					}
				}
				throw e;
			}
		}
		return affectedRows;
	}
	
	/**
	 * Maps Result set with the user object
	 * 
	 * @param resultSet
	 * @return mapped result object or null on Exception
	 */
	private Users mapResultSetToUsers(ResultSet resultSet) {

		try {
			Users user = new Users();
			user.setUserId( resultSet.getInt("user_id") );
			user.setUserName( resultSet.getString("username") );
			user.setEmail( resultSet.getString("email") );
	//		retUser.setPassword( resultSet.getString("password") ); 
			user.setRole( resultSet.getString("role"));
			return user;
		}catch(Exception e) {
			return null;
		}
		
	}
	
	
	
	
	
	
	
	
	
	
//	
//	public static void main(String[] args) {
//	    try {
//	    	UsersDAO ud = new UsersDAOImpl();
//	
//	    	
//	    	
//	    	Integer userId = ud.deleteUser(4);
//	
//	    	System.out.println(userId);
//	    	
//	    	
//	    }
//	    catch(SQLException e) {
//	    	e.printStackTrace();
//	    }
//	}
	
	
	
//	private static void displayUser(Users user)
//	{
//	    if (user != null) {
//	        System.out.println("User Details:");
//	        System.out.println("User ID   : " + user.getUserId());
//	        System.out.println("Username  : " + user.getUserName());
//	        System.out.println("Email     : " + user.getEmail());
//	        System.out.println("Role      : " + user.getRole());
//	        // Not printing password for security reasons
//	    } else {
//	        System.out.println("No user data to display.");
//	    }
//	}


}
