package com.quizkar.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import com.quizkar.entities.Users;
import com.quizkar.util.DBUtil;

public class UsersDAOImpl implements UsersDAO{

	//Returns UserId of added users
	public Integer addUser(Users user) throws SQLException
	{
																		// (RETURNING user_id) This part is used here because we want an user_id generated by postgresql
		String query = "INSERT INTO users (username, email, password, role) VALUES (?, ?, ?, ?) RETURNING user_id";
		Integer generatedId = null;
		
		try (Connection connection = DBUtil.getConnection();
		     PreparedStatement preparedStatement = connection.prepareStatement(query)) {
			
//			connection.setAutoCommit(false);
			
		    preparedStatement.setString(1, user.getUserName());
		    preparedStatement.setString(2, user.getEmail());
		    preparedStatement.setString(3, user.getPassword());
		    preparedStatement.setString(4, user.getRole());

		    ResultSet resultSet = preparedStatement.executeQuery();

		    
		    if (resultSet.next()) {
		        generatedId = resultSet.getInt("user_id");
//		        System.out.println("Inserted User ID: " + generatedId);
		    }
		}
		catch (SQLException e) {
		    e.printStackTrace();
		    throw e; 
		}
		return generatedId;
		
	}

	
	
//	
//	public static void main(String[] args) {
//	    try {
//	    	UsersDAO ud = new UsersDAOImpl();
//	
//	    	Users u = new Users();
//	    	u.setUserName("aa");
//	    	u.setEmail("aa@gmail.com");
//	    	u.setPassword("###");
//	    	u.setRole("admin");
//	    	
//	    	Integer userId = ud.addUser(u);
//	
//	    	System.out.println(userId);
//	    }
//	    catch(SQLException e) {
//	    	e.printStackTrace();
//	    }
//	}
	

}
