name: Neon Hello World Job

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'

jobs:
  run-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install postgresql-client -y

      - name: Run SQL on Neon DB
        run: |
          echo "Running SQL on Neon..."
          PGPASSWORD="${{ secrets.DB_PASSWORD }}" psql -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -c "DO $$ BEGIN RAISE NOTICE 'Hello World!'; END $$;"
