name: Run PostgreSQL Command

on:
  schedule:
    - cron: '0 2 * * 0' # Runs every Sunday at 2:00 AM UTC

jobs:
  run-postgres-command:
    runs-on: ubuntu-latest

    steps:
      - name: Run PostgreSQL Command
        env:
          PGPASSWORD: secrets.DB_PASSWORD # Replace 'your_password' with the actual password
        run: |
          psql -h secrets.DB_HOST -U secrets.DB_USER -d secrets.DB_NAME -c "SELECT hello world;"